### ISSUE TITLE
move to MediaWiki?

### ISSUE THREAD

**Issue by maxlath** [inventaire/jingo#6]
## Problem
Translation is done by looking at the canonical version (mostly English, but now also French for the articles around activities of the Inventaire Association) and then try to keep it up to date in some other language. This is done by a human comparing the existing versions, and trying to correct the differences, which is hard.

> If you have ever tried to translate content in [a wiki] without any tools, you know it does not scale. The translated versions get out of date and there is no way to track changes to the master page, so there are many half-translated and outdated translations without a clear overview of the overall status. Translators often feel discouraged when they cannot work with small manageable pieces of text. Translators don't find what to work on or what needs updating. The users also get confused by outdated information. [[source](https://www.mediawiki.org/wiki/Help:Extension:Translate#Content_translation)]

## Possible alternative
Move to a Mediawiki, were we could use the [`Extension:Translate`](https://www.mediawiki.org/wiki/Extension:Translate), which is much better tooled at informing of the out-dated text and the completeness of any language.

That would require that primary article writers get familiar with yet another markup, but it is very well documented :
* https://www.mediawiki.org/wiki/Help:Extension:Translate
* https://www.mediawiki.org/wiki/Help:Extension:Translate/Page_translation_example

One thing I couldn't find: is it possible to use different source languages? so that Association article can still primarily be in French, and then translated?

Other possible benefits of moving to MediaWiki:
* built-in image hosting

Possibly problematic:
* user authentification: it would be nice to keep the current setup of inventaire user <=> wiki user. It might be that [`Extension:Auth remoteuser`](https://www.mediawiki.org/wiki/Extension:Auth_remoteuser) could solve that problem

**Comment by jum-s** [comment]
> is it possible to use different source languages?

yes

> Administrators can change a specific page's language setting, using the Special:PageLanguage page, so that it can be used as a source page for translation.

[Source](https://www.mediawiki.org/wiki/Help:Extension:Translate/Page_translation_administration), and details [here](https://www.mediawiki.org/wiki/Manual:Language#Page_content_language)

**Comment by jum-s** [comment]
Im not sure user authentification is key here. Invites through [ImportUsers extension](https://www.mediawiki.org/wiki/Extension:ImportUsers) are quite easy to handle

**Comment by jum-s** [comment]
Could it be also a way to exit Transifex, and translate strings in mediawiki directly ? :)

**Comment by jum-s** [comment]
we could also centralize other wikis like https://github.com/inventaire/inventaire/wiki

**Comment by jum-s** [comment]
It seems that, as user authentication would be handled by a remote server (through the above mentioned [Extension:Auth_remoteuser](https://www.mediawiki.org/wiki/Extension:Auth_remoteuser)), there will be no sensitive information stored on the wiki. 

If this is confirmed, it would allow us to deploy it through [docker](https://www.mediawiki.org/wiki/Docker/Hub), avoiding installation of php and mariadb. Plus, docker is already installed on the server hosting the current wiki.

**Comment by jum-s** [comment]
I deliberately leave the auth on the side for the moment, as there is other less complex but timely issues to resolve:

- [x] create scripts to easily install extensions (based on `wikibase-docker` repo)
- [x] import translation extensions and configure it (to aim at the neat translation module of some wikimedia projects)
- [x] being able to upload images (especially to enable screenshots)
- [ ] transform jingo specific syntax into wikitext

**Comment by jum-s** [comment]
Current status

- most of the current wiki.inventaire.io and [inventaire.wiki](https://github.com/inventaire/inventaire/wiki) has been transferred. 
- an announcement has been posted on wiki.inventaire.io's homepage to discourage any more updates
- most images used in https://github.com/inventaire/inventaire-wiki/issues/1 are still an external GH link (no file upload) 
- there was an early misunderstanding about how to use the `<languages />` tag, it is now unnecessarily inserted inside the `<translate>` tag of some translated pages. please, future reviewer, put it outside when you encounter it.
- all pages currently asked for being translated are already being translated in french on the ~current~ old wiki.

Here are the list of the english titles (`<!-- LANG:EN, title="About the project"-->`) which have a french version to be copy/pasted to the new wiki:
- [ ] Are my inventory data also in the public database of books and authors?.fr
- [ ] Association.fr
- [ ] Communication channels.fr
- [ ] Data contribution guidelines.fr
- [ ] Data.fr
- [ ] Fabrique Lyonnaise des Communs 2017.fr
- [ ] Frequently Asked Questions.fr
- [x] How to add an author, a genre, or a subject to a book.fr
- [x] How to create a group.fr
- [ ] How to create an account.fr
- [x] How to edit books data.fr
- [ ] How to join an existing group.fr
- [ ] Legal notice.fr
- [ ] Privacy.fr
- [ ] Sandbox.fr
- [ ] Statuses.fr
- [x] Why is there no app?.fr
- [ ] inventaire wiki - How-to.fr
- [ ] magazines dvds.fr

**Comment by jum-s** [comment]
another possible centralisation into the mediawiki

https://github.com/inventaire/inventaire/tree/master/docs

**Comment by jum-s** [comment]
wiki has moved to https://github.com/inventaire/inventaire-mediawiki
